name: yin_utils
description: A new Flutter package.
version: 0.0.2
author: yin <yin_8023@163.com>
homepage: https://github.com/yx544806988/yin_utils.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2
  synchronized: ^2.1.0
  flutter_toast_pk: ^0.0.1               # Toast 提示


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


